Feature/mhc 9/create appointment controller and service
COM3014Group13/mental-health-app pull request #14
Opened 2023-03-30 00:45 UTC by Jennymaria98

2023-03-30 01:22 UTC, Alex-Williams01 commented
- So the reason why the build is failing is that " No property 'startTime' found for type 'Appointment' ". This is coming from the `findByStartTimeAfterAndEndTimeBefore` function in the appointment repository; it uses the name in the function, not the name of the arguments, so it's trying to find the field "startTime" rather than "appointmentStartTime" this is the same for "endTime".
![image](https://user-images.githubusercontent.com/73512853/228701488-de9586a8-786f-45a7-9f85-ed4d506b9233.png)
I think we should change all these variables to say just "startTime" and "endTime" to match rather than "appointmentStartTime" and "appointmentEndTime"

- After fixing that, we get another error "No property 'getAllAppointments' found for type 'Appointment'"; this again comes from the appointment repository. It doesn't know what to do with your `getAllAppointments`; this isn't something it can map to. All functions should be something like findByParamName.
![image](https://user-images.githubusercontent.com/73512853/228701877-a7c6bfb0-9e15-46be-a4e8-d6b31b8f0c95.png)
In this case, we can delete the "getAllAppointments" function as it doesn't work as intended; we will fix the method that calls it later. 
- Furthermore the `findAppointmentByid` is redundant; it doesn't get called as you use the default `findById` instead (which is correct). Therefore we can remove `findAppointmentByid`.
- Now, to fix the `getAppointmentByType` method, instead of calling `getAllAppointments`, we are going to create a new repository function `List<Appointment> findByType(String type);.`

Doing all this will fix your build; once your build is fixed, I'll comment on the PR on things to change further.

2023-04-03 20:18 UTC, Jennymaria98 commented
@Alex-Williams01 The build is successful.Kindly review it once

2023-04-04 00:41 UTC, Alex-Williams01 requested changes
Done a first pass-through, focused on things I noticed without running the code e.g. syntax. Once you've resolved all the comments we'll have a look at making sure it all interacts with the database properly and fix any bugs we find.

2023-04-04 00:41 UTC, Alex-Williams01 commented on appointment-service/src/main/java/com/com3014/appointmentservice/controller/appointmentservicecontroller.java
> +    public List<Appointment> getfindByStartTimeAfterAndEndTimeBefore(Time StartTime,Time EndTime)
nit: could all variables and functions start with lowercase, then following words start uppercase. E.g. startTime. Also could we call this function getApppointmentsBetween or something

2023-04-04 00:41 UTC, Alex-Williams01 commented on appointment-service/src/main/java/com/com3014/appointmentservice/model/Appointment.java
> +    private Time StartTime;
could this be `startTime` and `endTime`

2023-04-04 00:41 UTC, Alex-Williams01 commented on appointment-service/src/main/java/com/com3014/appointmentservice/model/Appointment.java
> +    public Appointment(UUID id,UUID DOC_ID,Time StartTime, Time EndTime,UUID Patient_ID,String summary,String Type,String Status)
same as above

2023-04-04 00:41 UTC, Alex-Williams01 commented on appointment-service/src/main/java/com/com3014/appointmentservice/service/AppointmentService.java
> -    public List<Appointment> getAllAppointments()
could we add this method back, this is correct functionality

2023-04-04 00:41 UTC, Alex-Williams01 commented on appointment-service/src/main/java/com/com3014/appointmentservice/controller/appointmentservicecontroller.java
> +public class appointmentservicecontroller
Could class names be Sentence Cased, also can we name this the AppointmentController rather than AppointmentServiceController

2023-04-04 00:41 UTC, Alex-Williams01 commented on appointment-service/src/main/java/com/com3014/appointmentservice/controller/appointmentservicecontroller.java
> +    private final  AppointmentService appointmentservice;
could this variable be camel cased, appointmentService

2023-04-04 00:41 UTC, Alex-Williams01 commented on appointment-service/src/main/java/com/com3014/appointmentservice/controller/appointmentservicecontroller.java
> +    @Autowired
We should put this @Autowired annotation on the constructor of the AppointmentController rather than this field. It makes unit testing easier

2023-04-04 00:41 UTC, Alex-Williams01 commented on appointment-service/src/main/java/com/com3014/appointmentservice/controller/appointmentservicecontroller.java
> +    {
nitpick: this is personal preference but could we put curly brackets on the same line as the method signature. I.e

```
public AppointmentController(AppointmentService appointmentService) {
    this.appointmentService = appointmentService ;
}
```

same for all methods in all classes

2023-04-04 00:41 UTC, Alex-Williams01 commented on appointment-service/src/main/java/com/com3014/appointmentservice/controller/appointmentservicecontroller.java
> +    @GetMapping("/{id}")
what happened to the formatting here? (Indenting of the method)

2023-04-04 00:41 UTC, Alex-Williams01 commented on appointment-service/src/main/java/com/com3014/appointmentservice/controller/appointmentservicecontroller.java
> +    @GetMapping("/{Patient_ID}")
nitpick: could we use `"/{patientId}"` just so the variable can be camelcase

2023-04-04 00:41 UTC, Alex-Williams01 commented on appointment-service/src/main/java/com/com3014/appointmentservice/controller/appointmentservicecontroller.java
> +    public List<Appointment> getfindByStartTimeAfterAndEndTimeBefore(Time StartTime,Time EndTime)
also this function doesnt have a getmapping annotation on it

2023-04-04 00:41 UTC, Alex-Williams01 commented on appointment-service/src/main/java/com/com3014/appointmentservice/controller/appointmentservicecontroller.java
> +    @GetMapping("/Type")
how do I specify the type when hitting this endpoint? could we make type a RequestParam with the annotation `@RequestParam`

2023-04-04 00:41 UTC, Alex-Williams01 commented on appointment-service/src/main/java/com/com3014/appointmentservice/exceptions/AppointmentIdnotFoundException.java
> +public class AppointmentIdnotFoundException extends RuntimeException {
N at the start of the word not should be capital

2023-04-04 00:41 UTC, Alex-Williams01 commented on appointment-service/src/main/java/com/com3014/appointmentservice/model/Appointment.java
> +    public Appointment(UUID id,UUID DOC_ID,Time StartTime, Time EndTime,UUID Patient_ID,String summary,String Type,String Status)
we also shouldnt be passing in the id as a param, we are setting it as a random UUID below, we should still pass in docId and patientId though

2023-04-04 00:41 UTC, Alex-Williams01 commented on appointment-service/src/main/java/com/com3014/appointmentservice/model/Appointment.java
> +       this.DOC_ID=UUID.randomUUID();
for docId and PatientId they need to be using the arguments passed into the method rather than being generated (however this.id is fine being randomUUID)

2023-04-04 00:41 UTC, Alex-Williams01 commented on appointment-service/src/main/java/com/com3014/appointmentservice/model/Appointment.java
> +    private UUID DOC_ID;
can this be `docId`

2023-04-04 00:41 UTC, Alex-Williams01 commented on appointment-service/src/main/java/com/com3014/appointmentservice/model/Appointment.java
> +    private UUID Patient_ID;
same as `docId`, can this be `patientId`

2023-04-04 00:41 UTC, Alex-Williams01 commented on appointment-service/src/main/java/com/com3014/appointmentservice/model/json/AppointmentJson.java
> +     private UUID DOC_ID;
same as appointment class, `docId`

2023-04-04 00:41 UTC, Alex-Williams01 commented on appointment-service/src/main/java/com/com3014/appointmentservice/model/json/AppointmentJson.java
> +     private Time StartTime;
same as appointment class `startTime`

2023-04-04 00:41 UTC, Alex-Williams01 commented on appointment-service/src/main/java/com/com3014/appointmentservice/model/json/AppointmentJson.java
> +     private Time EndTime;
as above

2023-04-04 00:41 UTC, Alex-Williams01 commented on appointment-service/src/main/java/com/com3014/appointmentservice/model/json/AppointmentJson.java
> +     private UUID Patient_ID;
as above

2023-04-04 00:41 UTC, Alex-Williams01 commented on appointment-service/src/main/java/com/com3014/appointmentservice/model/json/AppointmentJson.java
> +     private UUID id;
we dont need an id in the json (or an `@Id' annotation)

2023-04-04 00:41 UTC, Alex-Williams01 commented on appointment-service/src/main/java/com/com3014/appointmentservice/model/json/AppointmentJson.java
> +     public AppointmentJson(UUID id,UUID DOC_ID,Time StartTime, Time EndTime,UUID Patient_ID,String summary,String Type,String Status)
we can remove the first id field as its not necessary for the JSON

2023-04-04 00:41 UTC, Alex-Williams01 commented on appointment-service/src/main/java/com/com3014/appointmentservice/model/json/AppointmentJson.java
> +        this.DOC_ID=UUID.randomUUID();
can `docId` and `patientId` be set to their params rather than random

2023-04-04 00:41 UTC, Alex-Williams01 commented on appointment-service/src/main/java/com/com3014/appointmentservice/repository/AppointmentRepository.java
> +    Optional<Appointment> findAppointmentByid(UUID id);
I believe this `Optional<Appointment> findAppointmentByid(UUID id);` isn't being used so we can delete it. The `getAppointmentById` method in the `AppointmentService` rightly uses `findById` which is given to us by MongoRepository

2023-04-04 00:41 UTC, Alex-Williams01 commented on appointment-service/src/main/java/com/com3014/appointmentservice/service/AppointmentService.java
> + @Autowired
can we add a constructor and add the `@Autowired` annotation to that instead. It should look like this:
```
private final AppointmentRepository appointmentRepository;

@Autowired
public AppointmentService(AppointmentRepository appointmentRepository) {
    this.appointmentRepository = appointmentRepository;
}
```

2023-04-04 00:41 UTC, Alex-Williams01 commented on appointment-service/src/main/java/com/com3014/appointmentservice/service/AppointmentService.java
> +    public Appointment updateappointment(UUID id,AppointmentJson json) {
Can we capitalise the a: `updateAppointment`

2023-04-04 00:41 UTC, Alex-Williams01 commented on appointment-service/src/main/java/com/com3014/appointmentservice/service/AppointmentService.java
> +        ((Appointment) appointment).setStartTime(json.getStartTime());
I think we can remove all this casting and just have `appointment.setStartTime(json.getStartTime())` etc...

2023-04-04 00:41 UTC, Alex-Williams01 commented on appointment-service/src/main/java/com/com3014/appointmentservice/service/AppointmentService.java
> +        appointmentrepo.delete(deleteappointmentByIdorThrow(id));
can we call `getappointmentByIdorThrow` rather than `deleteappointmentByIdorThrow` as its misleading. I think we should remove the `deleteappointmentByIdorThrow` method

2023-04-04 00:41 UTC, Alex-Williams01 commented on appointment-service/src/main/java/com/com3014/appointmentservice/service/AppointmentService.java
> +    public Appointment getappointmentByIdorThrow(UUID id)
camelCase: `getAppointmentByIdOrThrow`

2023-04-04 00:41 UTC, Alex-Williams01 commented on appointment-service/src/main/java/com/com3014/appointmentservice/service/AppointmentService.java
> +    public Optional<Appointment> getAppointmentByPatient_ID(UUID Patient_ID)
can we call this `getAppointmentByPatientId` with the parameter `patientId`

2023-04-04 00:41 UTC, Alex-Williams01 commented on appointment-service/src/main/java/com/com3014/appointmentservice/service/AppointmentService.java
> +        return appointmentrepo.findById(Patient_ID);
this will find by appointmentId and not by patientId. We need to add a function to the AppointmentRepo that is `List<Appointment> findByPatientID(UUID id);` which will mean this method will need to return a `List<Appointment>` rather than `Optional<Appointment>`, the same with the controller method calling this method.

2023-04-04 00:41 UTC, Alex-Williams01 commented on appointment-service/src/main/java/com/com3014/appointmentservice/service/AppointmentService.java
> +    return appointmentrepo.findByType(Type);
I think this needs to be indented

2023-04-11 10:40 UTC, Alex-Williams01 requested changes
I think we're almost there. Just some minor comments, when these comments are addressed, I think we will be able to merge.

2023-04-11 10:40 UTC, Alex-Williams01 commented on appointment-service/src/main/java/com/com3014/appointmentservice/model/Appointment.java
> +    private Time startTime;
Given that we need time and date, we should change everything from `Time` to something that supports date as well, I think we should use `Instant`. so startTime and endTime in this class, the AppointmentJson class and any method parameters in all classes should be changed

2023-04-11 10:40 UTC, Alex-Williams01 commented on appointment-service/src/main/java/com/com3014/appointmentservice/controller/AppointmentController.java
> +    @GetMapping("/{patientId}")
I think we need to change this URL to something like `'/patient/{patientId}'` as it currently will conflict with the `getAppointmentById`

2023-04-11 10:40 UTC, Alex-Williams01 commented on appointment-service/src/main/java/com/com3014/appointmentservice/controller/AppointmentController.java
> +    public List<Appointment> getAllAppointments(@RequestParam(name = "startTime", required = false) Time startTime, @RequestParam(name = "endTime", required = false) Time endTime) {
As per the comment in the Appointment class, can we change the `Time` params here to `Instant`

2023-04-11 10:40 UTC, Alex-Williams01 commented on appointment-service/src/main/java/com/com3014/appointmentservice/model/Appointment.java
> +    private String status;
We decided to change `status` to instead be `cancelled`, can we change this to `private Boolean cancelled;` and update all methods in this class? Do this for the `AppointmentJson` class as well

2023-04-11 10:40 UTC, Alex-Williams01 commented on appointment-service/src/main/java/com/com3014/appointmentservice/model/json/AppointmentJson.java
> +     private UUID id;
We can remove this id field entirely from this class and all references to it (for this Json class, keep the normal Appointment.java one)

2023-04-11 10:40 UTC, Alex-Williams01 commented on appointment-service/src/main/java/com/com3014/appointmentservice/model/json/AppointmentJson.java
> +     private String status;
as per the appointment class comment, can we change status to a Boolean called cancelled (and update all methods in this file and other files that reference it)

2023-04-11 10:40 UTC, Alex-Williams01 commented on appointment-service/src/main/java/com/com3014/appointmentservice/repository/AppointmentRepository.java
> +    List<Appointment> findByStartTimeAfterAndEndTimeBefore(Time startTime,Time endTime);
we can update the Time params to Instant

2023-04-12 16:54 UTC, Alex-Williams01 approved these changes
Looks good, just added the final changes myself as they were trivial.

2023-04-13 16:44 UTC, merged