Features/mhc 33/appointment ticket
COM3014Group13/mental-health-app pull request #17
Opened 2023-04-06 15:16 UTC by ah01567

This section contains the following: 
  - (Upcoming - Previous - Cancelled) appointment tickets in HomePage.vue
  - Available doctor tickets in BookAppointmentPage.vue 
  - added v-for and v-if to generate automatic tickets using PROPS

2023-04-07 00:14 UTC, Alex-Williams01 requested changes
Looking good! Just a couple things noted

2023-04-07 00:14 UTC, Alex-Williams01 commented on frontend/src/components/AvailableDocTicket.vue
> +.appointment-type-radios__radio-item {
This css looks like this to me? idk if I'm doing something wrong?
![image](https://user-images.githubusercontent.com/73512853/230514487-7928a8be-eeca-4203-9cea-7a7af434b2ab.png)
Also you can't select a radio. I would change it so this CSS is:
```
.appointment-type-radios__radio-item {
  flex: 0 0 50%;
  border-radius: 0;
  margin-left: 0 !important;
  padding: 5px;
}
```
then in the BookAppointmentPage have:
```
<AppointmentBookingSection ref="section4" title="Which doctor you like an appointment with?" label="Please chose one of the following available doctors.">
      <b-form-radio-group buttons button-variant="outline-secondary" class="doctor-radios" :disabled="!section3Complete">
        <AvailableDocTicket :key="index" v-for="(doctor, index) in availableDoctors" :doctor="doctor"></AvailableDocTicket>
      </b-form-radio-group>
</AppointmentBookingSection>
```
with the CSS:
```
.doctor-radios {
    display: flex !important;
    flex-wrap: wrap;
  }
```
which should look like:
![image](https://user-images.githubusercontent.com/73512853/230514877-deec14f1-6407-47dd-a86f-a7edc3486c62.png)

2023-04-07 00:14 UTC, Alex-Williams01 commented on frontend/src/components/AvailableDocTicket.vue
> +.appointment-type-radios__radio-item:hover {
if you do the css above this can be removed

2023-04-07 00:14 UTC, Alex-Williams01 commented on frontend/src/pages/BookAppointmentPage.vue
> +      availableDoctors: [
we need a doctor field for the radio to v-model to. (Check it works with the vue dev tools chrome extension). Also the final submit button should now be disabled based on doctor selected not on the previous section

2023-04-07 00:14 UTC, Alex-Williams01 commented on frontend/src/pages/BookAppointmentPage.vue
> +          doctor: 'Ahmed Henine',
can these doctors have a docId which will be the value of the radio button? Can we also rename the doctor field in each one to be name instead? Heres an example of a single doctor the backend will return
```
{
		"id": "0e5c9e0e-65a1-48c1-a8b3-84fe12204055",
		"username": "lmao@surrey.ac.uk",
		"firstName": "Alex",
		"lastName": "Williams",
		"authorities": [
			{
				"authority": "DOCTOR"
			}
		]
	}
```

2023-04-07 00:14 UTC, Alex-Williams01 commented on frontend/src/pages/HomePage.vue
> +      upcomingAppointments: [
rather than seperate data, to more accurately represent how we will get appointments from the backend could we have one data field that has all appointments (see one of my first comments). Then we can have computed properties e.g.
```
previousAppointments() {
      return this.appointments
          .filter(appointment => appointment.cancelled === false)
          .filter(appointment => new Date(appointment.endTime) < new Date());
    },
```

2023-04-07 00:14 UTC, Alex-Williams01 commented on frontend/src/pages/HomePage.vue
>                <b-card-body>
were we planning to do the whole limit to 3 appointment tickets on screen per section and have a scroll or will that be a separate JIRA task?

2023-04-09 13:06 UTC, ah01567 commented on frontend/src/components/AppointmentTicket.vue
> +        <b-card class="ticket" bg-variant="light" :title="appointment.date">
done ✅

2023-04-09 14:02 UTC, ah01567 commented on frontend/src/components/AppointmentTicket.vue
> +    <template v-if="appointment.status === 'upcoming'">
done ✅

2023-04-09 14:09 UTC, ah01567 commented on frontend/src/components/AppointmentTicket.vue
> +                Your appointment with Dr. <b>{{ appointment.doctor }}</b> is now confirmed. You will be able to join the appointment 10min before the booked timing.
done ✅

2023-04-09 14:10 UTC, ah01567 commented on frontend/src/components/AppointmentTicket.vue
> +    <template v-if="appointment.status === 'cancelled'">
done ✅

2023-04-09 14:10 UTC, ah01567 commented on frontend/src/components/AppointmentTicket.vue
> +    <template v-if="appointment.status === 'previous'">
done ✅

2023-04-09 14:18 UTC, ah01567 commented on frontend/src/components/AppointmentTicket.vue
> +            Your appointment with Dr. <b>{{ appointment.doctor }}</b> has terminated. However, you are still able to access your previous chat with the docor, by clicking the button below.
done ✅

2023-04-09 14:20 UTC, ah01567 commented on frontend/src/components/AvailableDocTicket.vue
> +<template v-if="availableDoctors.status === 'free'">
done ✅

2023-04-09 14:21 UTC, ah01567 commented on frontend/src/components/AvailableDocTicket.vue
> +    </b-form-radio-group>
done ✅

2023-04-09 14:31 UTC, ah01567 commented on frontend/src/components/AvailableDocTicket.vue
> +.appointment-type-radios__radio-item {
done ✅

2023-04-09 14:53 UTC, ah01567 commented on frontend/src/pages/BookAppointmentPage.vue
> +          doctor: 'Ahmed Henine',
done ✅

2023-04-09 15:08 UTC, ah01567 commented on frontend/src/pages/BookAppointmentPage.vue
> +      availableDoctors: [
done ✅

2023-04-09 16:25 UTC, Alex-Williams01 requested changes
Looking good! Just a couple comments / questions

2023-04-09 16:25 UTC, Alex-Williams01 commented on frontend/src/pages/HomePage.vue
> +    formattedDate() {
I think these computed properties go in the AppointmentTicket.vue component as they are specifically about individual tickets

2023-04-09 16:25 UTC, Alex-Williams01 commented on frontend/src/pages/HomePage.vue
> +    appointments: [
looking good

2023-04-09 16:25 UTC, Alex-Williams01 commented on frontend/src/pages/HomePage.vue
> +                <AppointmentTicket v-for="(appointment, index) in cancelledAppointments" :key="index" :appointment="appointment"/>
I assume the next commits will add the computed properties that these v-fors reference, in this file that filter appointments for cancelled previous and upcoming

2023-04-09 16:25 UTC, Alex-Williams01 commented on frontend/src/pages/BookAppointmentPage.vue
> +      this.proceedToSection("section4Complete", this.$refs.section5);
we will need to define a section4Complete data item like the other sections for this to work

2023-04-09 16:25 UTC, Alex-Williams01 commented on frontend/src/pages/BookAppointmentPage.vue
> +            <b-form-radio-group buttons button-variant="outline-secondary" class="doctor-radios" :disabled="!section3Complete" @click="proceedToSection5">
Im not sure if this `@click` will actually work as its a radio group

2023-04-09 16:25 UTC, Alex-Williams01 commented on frontend/src/pages/BookAppointmentPage.vue
> +          <b-button type="submit" variant="success" class='booking-section-btn-proceed' :disabled="!section4Complete">Book appointment</b-button><br>
given `@click` might not work in this `:disabled="!section4Complete"` maybe we instead just check if the selectedDoctor is empty or not

2023-04-09 16:25 UTC, Alex-Williams01 commented on frontend/src/pages/BookAppointmentPage.vue
> +      availableDoctors: [
I believe this was talking about v-modeling the selected doctor e.g. like you have selectedTime rather than using the correct data for available doctors.

2023-04-09 16:25 UTC, Alex-Williams01 commented on frontend/src/pages/BookAppointmentPage.vue
> +          "authorities": [
This is my bad, this can be changed from
```
"authorities": [
    {
        "authority": "DOCTOR"
    }
]
```
to
```
"role": "DOCTOR"
```

2023-04-09 16:25 UTC, Alex-Williams01 commented on frontend/src/components/AvailableDocTicket.vue
> +    available: {
I think this will need to be called doctor rather than available

2023-04-09 16:25 UTC, Alex-Williams01 commented on frontend/src/components/AvailableDocTicket.vue
> +      <p>{{ doctor.hospital }}</p>
I will change the backend to add a hospital to the user if they have one

2023-04-09 16:25 UTC, Alex-Williams01 commented on frontend/src/components/AvailableDocTicket.vue
> +      <h4>Dr. {{ doctor.doctor }}</h4>
i assume this will need to be like firstName + lastName or something right?

2023-04-09 16:25 UTC, Alex-Williams01 commented on frontend/src/components/AvailableDocTicket.vue
> +  <b-form-radio class="appointment-type-radios__radio-item"  :value="doctor.docId">
I believe in the doctor table / json `docId` is just `id`. It's only `docId` when it's referenced in the appointments table / json

2023-04-10 09:19 UTC, ah01567 commented on frontend/src/pages/HomePage.vue
> +    formattedDate() {
They should go where the properties are innit ? i was thinking to take everything to AppointmentTicket.vue (props and methods)

2023-04-10 09:22 UTC, ah01567 commented on frontend/src/pages/HomePage.vue
> +                <AppointmentTicket v-for="(appointment, index) in cancelledAppointments" :key="index" :appointment="appointment"/>
yup

2023-04-13 02:44 UTC, Alex-Williams01 approved these changes

2023-04-13 02:49 UTC, merged